### ISSUE TITLE
Package that can be installed with pip

### ISSUE THREAD

**Issue by ghing** [JoshData/convert-outlook-msg-file#1]
First, thank you for this. I've found it to be really useful at at a time when my colleague needed exactly this tool.

It would be great this into a Python package with a setup.py that will install dependencies with pip and automatically make `outlookmsgfile.py` on the system path.

I can do this packaging work an send a pull request, but I wanted to make sure you hadn't already done this or were in-progress with this.

**Comment by JoshData** [comment]
Wow that was fast. :) Usually I post things and then it takes years before it gets into anyone else's hands.

That'd be great! Thanks!

**Comment by ghing** [comment]
Thanks for the quick response. Look for a PR later this week.

**Comment by joelgenter** [comment]
Any development on this? Installing via pip would be very useful.
