### ISSUE TITLE
Don't print to sys.stderr, use logging instead

### ISSUE THREAD

**Issue by MartijnVdS** [JoshData/convert-outlook-msg-file#17]
Python includes the "logging" library, which offers a configurable way to output (diagnostic) information.

Currently, the library uses `print` to `sys.stderr` when things go wrong. Because of this, the log parser we use gets confused sometimes, as it expects all output to be structured as JSON objects.

Using `logging` would allow us to disable or format logs from this module. A default configuration could be included that keeps output the same (or very similar) to the way it currently is, when running `outlookmsgfile.py` as a standalone script.

Would you be open to a pull request?

**Comment by JoshData** [comment]
Sure, thanks!

**Comment by MartijnVdS** [comment]
https://github.com/JoshData/convert-outlook-msg-file/pull/19

**Comment by MartijnVdS** [comment]
Since #19 was merged some time ago, I think this issue can be closed.
