### ISSUE TITLE
Use ATTACH_LONG_FILENAME instead of DOS-type short file name

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [JoshData/convert-outlook-msg-file#3]
Before:
```
filename = props.get("ATTACH_FILENAME") or props.get("DISPLAY_NAME")```
```
After:
```
filename = props.get("ATTACH_LONG_FILENAME") or props.get("ATTACH_FILENAME") or props.get("DISPLAY_NAME")```
```

**Comment by JoshData** [comment]
Good idea! Would you mind opening a pull request so it's easy for me to merge in the change?

**Comment by Sicos1977** [comment]
I don't know if python can call .NET assemblies but otherwise you also can use my library to convert MSG files to EML --> https://github.com/Sicos1977/MSGReader

**Comment by VelizarVESSELINOV** [comment]
@Sicos1977 depends if you can install your C# package with all the dependencies in one command line on all variations of OS (Linux, Mac, etc.). Last time when I tested this was not a big success, but I heard that C# portability and deployment is improving with the time.

**Comment by Sicos1977** [comment]
MSGReader is build against .NET STANDARD 2.0 so it should also work on Linux and Mac...

**Comment by aoshiken** [comment]
I think it's safe to close this issue
