### ISSUE TITLE
Add license 

### ISSUE THREAD

**Issue by gojefferson** [JoshData/convert-outlook-msg-file#5]
Hi @JoshData, 

This library works great. Are you able to add an MIT license to it?

Thank you

**Comment by JoshData** [comment]
Yes, for sure. Would you mind submitting a pull request?

**Comment by gojefferson** [comment]
Done. Here it is: https://github.com/JoshData/convert-outlook-msg-file/pull/6

**Comment by Nothing4You** [comment]
how about closing this considering #6 is merged?
